### ISSUE TITLE
Error on UglifyJs build

### ISSUE THREAD

**Issue by carromeu** [slexx1234/v-webp#2]
Hi team,

First, thanks for this package! It's really useful.

I am using it whith VueJS and Webpack. On build, occurs:

ERROR in static/js/vendor.399bd106dde2d3f0edeb.js from UglifyJs
Unexpected token: name (WebP) [./node_modules/v-webp/index.js:1,0][static/js/vendor.399bd106dde2d3f0edeb.js:100841,6]

Any suggestion to fix?

**Comment by slexx1234** [comment]
Uglify cannot parse ES6, it will throw you syntax errors. Post-process your generated JS with babel, or use a different minifier.
